<?php
/** @var \Magento\Framework\View\Element\Template $block */

?>

<form class="form form-edit-account"
      action="<?= $escaper->escapeUrl($block->getUrl('customerStatus/index/save')) ?>"
      method="post" id="customer_status"
      data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset info">

        <?= $block->getBlockHtml('formkey') ?>

        <div class="field customer-status">
            <label class="label" for="customer_status">
                <span><?= $escaper->escapeHtml(__('Change Status')) ?></span>
            </label>
            <input type="text" name="customer_status" id="customer_status" class="input-text"
                   data-validate="{required:true}" title="<?= $escaper->escapeHtmlAttr(__('Change Status')) ?>" />
        </div>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $escaper->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
    </div>
</form>
